//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLYAZAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLYAZAR()
        {
            this.TBLKITAP = new HashSet<TBLKITAP>();
        }
    
        public int? ID { get; set; }

        [Required(ErrorMessage = " Bu alan zorunludur.")]
        public string AD { get; set; }

        [Required(ErrorMessage = " Bu alan zorunludur.")]
        public string SOYAD { get; set; }
        public string DETAY { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKITAP> TBLKITAP { get; set; }
    }
}
